/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntranceRouteImport } from './routes/entrance'
import { Route as IndexRouteImport } from './routes/index'

const EntranceRoute = EntranceRouteImport.update({
  id: '/entrance',
  path: '/entrance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrance': typeof EntranceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrance': typeof EntranceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrance': typeof EntranceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entrance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entrance'
  id: '__root__' | '/' | '/entrance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntranceRoute: typeof EntranceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrance': {
      id: '/entrance'
      path: '/entrance'
      fullPath: '/entrance'
      preLoaderRoute: typeof EntranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntranceRoute: EntranceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
